<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="282" started-at="2017-11-08T07:50:21Z" finished-at="2017-11-08T07:50:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="282" started-at="2017-11-08T07:50:21Z" finished-at="2017-11-08T07:50:21Z">
      <class name="com.virphy.TestNG.Beforemethod">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.virphy.TestNG.Beforemethod@31ef45e3]" name="beforeMethod" is-config="true" duration-ms="31" started-at="2017-11-08T13:20:21Z" finished-at="2017-11-08T13:20:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="login()[pri:0, instance:com.virphy.TestNG.Beforemethod@31ef45e3]" name="login" duration-ms="17" started-at="2017-11-08T13:20:21Z" finished-at="2017-11-08T13:20:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [logout] but found [doaction]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [logout] but found [doaction]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at com.virphy.TestNG.Beforemethod.login(Beforemethod.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="logout()[pri:0, instance:com.virphy.TestNG.Beforemethod@31ef45e3]" name="logout" duration-ms="0" started-at="2017-11-08T13:20:21Z" finished-at="2017-11-08T13:20:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.virphy.TestNG.Beforemethod@31ef45e3]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2017-11-08T13:20:21Z" finished-at="2017-11-08T13:20:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.virphy.TestNG.Beforemethod@31ef45e3]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-11-08T13:20:21Z" finished-at="2017-11-08T13:20:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.virphy.TestNG.Beforemethod@31ef45e3]" name="afterMethod" is-config="true" duration-ms="0" started-at="2017-11-08T13:20:21Z" finished-at="2017-11-08T13:20:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="doaction()[pri:0, instance:com.virphy.TestNG.Beforemethod@31ef45e3]" name="doaction" duration-ms="0" started-at="2017-11-08T13:20:21Z" depends-on-methods="com.virphy.TestNG.Beforemethod.login" finished-at="2017-11-08T13:20:21Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Beforemethod.doaction()[pri:0, instance:com.virphy.TestNG.Beforemethod@31ef45e3] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Beforemethod.doaction()[pri:0, instance:com.virphy.TestNG.Beforemethod@31ef45e3] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1092)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doaction -->
      </class> <!-- com.virphy.TestNG.Beforemethod -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
